Fix environment variable issues
sillsdev/aws-kubectl pull request #2
Opened 2021-08-20 13:47 UTC by jmgrady

This PR contains the following improvements:
- README.md headers are not so bold as before
- Changed environment variable `SECRET_NAME` to `PULL_SECRET_NAME` to make it more specific
- Corrected `AWS_REGION` to `AWS_DEFAULT_REGION` as expected by the `aws-cli`
- Replaced hard-coded secret name with `${PULL_SECRET_NAME}` in `ecr-get-login.sh`
- Add `bash` script to build the docker image and push it to Docker Hub

2021-08-20 16:56 UTC, johnthagen commented
___
*[build.sh, line 2 at r1](https://reviewable.io/reviews/sillsdev/aws-kubectl/2#-MhZU8R4BpSE6aw_dYnV:-MhZU8R4BpSE6aw_dYnW:bnt1ivd) ([raw file](https://github.com/sillsdev/aws-kubectl/blob/735915e94284e3d2968dea7765c2d6a1c81b232d/build.sh#L2)):*
> ```Shell
> #! /bin/bash
> ```

Could a brief usage guide be added to the top of the script with an example? I see this can take two arguments, for example, and it wasn't immediately clear how this should be used.


<!-- Sent from Reviewable.io -->

2021-08-20 16:56 UTC, johnthagen commented
___
*[build.sh, line 3 at r1](https://reviewable.io/reviews/sillsdev/aws-kubectl/2#-MhZUTLC-vClgM5zuy--:-MhZUTLC-vClgM5zuy-0:b-1nvpe1) ([raw file](https://github.com/sillsdev/aws-kubectl/blob/735915e94284e3d2968dea7765c2d6a1c81b232d/build.sh#L3)):*
> ```
> sillsdev/aws-kubectl
> ```

This string is used a number of times throughout this script. Could it be assigned once to a variable and reused?


<!-- Sent from Reviewable.io -->

2021-08-20 16:58 UTC, johnthagen requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/aws-kubectl/2)* status: all files reviewed, 2 unresolved discussions (waiting on @jmgrady)



<!-- Sent from Reviewable.io -->

2021-08-20 18:25 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/aws-kubectl/2)* status: all files reviewed, 2 unresolved discussions (waiting on @johnthagen)

___
*[build.sh, line 2 at r1](https://reviewable.io/reviews/sillsdev/aws-kubectl/2#-MhZU8R4BpSE6aw_dYnV:-MhZnKQq48PGckCY58hQ:b-896fix) ([raw file](https://github.com/sillsdev/aws-kubectl/blob/735915e94284e3d2968dea7765c2d6a1c81b232d/build.sh#L2)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Could a brief usage guide be added to the top of the script with an example? I see this can take two arguments, for example, and it wasn't immediately clear how this should be used.
</blockquote></details>

Done.
___
*[build.sh, line 3 at r1](https://reviewable.io/reviews/sillsdev/aws-kubectl/2#-MhZUTLC-vClgM5zuy--:-MhZninT0cFIGcs5H1MZ:b-896fix) ([raw file](https://github.com/sillsdev/aws-kubectl/blob/735915e94284e3d2968dea7765c2d6a1c81b232d/build.sh#L3)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

> ```
> sillsdev/aws-kubectl
> ```

This string is used a number of times throughout this script. Could it be assigned once to a variable and reused?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-23 15:17 UTC, imnasnainaec reviewed
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/aws-kubectl/2)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @jmgrady and @johnthagen)

___
*[build.sh, line 13 at r2](https://reviewable.io/reviews/sillsdev/aws-kubectl/2#-Mhn_bEsET4Km7IQ-nad:-Mhn_bEsET4Km7IQ-nae:bn7khg4) ([raw file](https://github.com/sillsdev/aws-kubectl/blob/af3b626cc7ce1e5927d169cc48adf8a8d50eecd3/build.sh#L13)):*
> ```
> It will then for each tag provided as a command argument, it will:
> ```
Redundant "it will"
___
*[scripts/ecr-get-login.sh, line 27 at r2](https://reviewable.io/reviews/sillsdev/aws-kubectl/2#-Mhn_8Lf7dhIx37P90H0:-Mhn_8Lg0K0f50I2ILcI:bpmuox8) ([raw file](https://github.com/sillsdev/aws-kubectl/blob/af3b626cc7ce1e5927d169cc48adf8a8d50eecd3/scripts/ecr-get-login.sh#L27)):*
> ```
> echo kubectl patch serviceaccount default -p "{\"imagePullSecrets\":[{\"name\":${PULL_SECRET_NAME}}]}"
> ```
So quotes aren't needed around the thing that follows "name"?


<!-- Sent from Reviewable.io -->

2021-08-23 15:24 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/aws-kubectl/2)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @imnasnainaec and @johnthagen)

___
*[build.sh, line 13 at r2](https://reviewable.io/reviews/sillsdev/aws-kubectl/2#-Mhn_bEsET4Km7IQ-nad:-MhnaGFR9kes8riFcLBQ:b-896fix) ([raw file](https://github.com/sillsdev/aws-kubectl/blob/af3b626cc7ce1e5927d169cc48adf8a8d50eecd3/build.sh#L13)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
> It will then for each tag provided as a command argument, it will:
> ```
Redundant "it will"
</blockquote></details>

Done.
___
*[scripts/ecr-get-login.sh, line 27 at r2](https://reviewable.io/reviews/sillsdev/aws-kubectl/2#-Mhn_8Lf7dhIx37P90H0:-MhnavrbBJypEnQgO7KE:bow8wq8) ([raw file](https://github.com/sillsdev/aws-kubectl/blob/af3b626cc7ce1e5927d169cc48adf8a8d50eecd3/scripts/ecr-get-login.sh#L27)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
> echo kubectl patch serviceaccount default -p "{\"imagePullSecrets\":[{\"name\":${PULL_SECRET_NAME}}]}"
> ```
So quotes aren't needed around the thing that follows "name"?
</blockquote></details>

Yes, I believe they are needed.  The job is not failing but when I look at the service account, I see that it has an old image pull secret.  I will fix it and let you know when I have tested it.


<!-- Sent from Reviewable.io -->

2021-08-23 17:51 UTC, imnasnainaec approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/aws-kubectl/2)* status: all files reviewed, 2 unresolved discussions (waiting on @johnthagen)



<!-- Sent from Reviewable.io -->

2021-08-23 17:54 UTC, merged